import 'focus-components/style';
import './layout.scss';
import './header.scss';
import './menu-left.scss';
import './movie-card.scss';
import './person-card.scss';
import './picture.scss';
import './poster.scss';
import './trailer.scss';
